image:
  - Visual Studio 2017

branches:
  only:
    - master
    - appveyor

environment:
  matrix:
    - BUILD_SYSTEM: CMake
      GENERATOR: Visual Studio 15 2017 Win64
      CONFIG_TYPE: Release

build_script:
  - cmake -G "Visual Studio 15 2017 Win64" ./CMakeLists.txt
  - cmake --build . --config Release -- /property:Prefer32bit=false /p:Platform=x64
